name: Test & Build Pipeline

on: 
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # New Caching step
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        pip install pytest flake8 httpx

    # 4. Run tests
    - name: Run tests
      run: pytest tests/ --maxfail=1 --disable-warnings -q

    # 5. Lint code
    - name: Link with flake8
      run:  flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics

    # 6. Build Docker image (only on push to main)
    # - name: Build Docker image
    #   if: github.event_name == 'push'
    #   run: |
    #     docker build \
    #     -t autoops-ai:latest \
    #     -t autoops-ai:${{ github.sha }} \
    #     .

    # 6. Login to Docker Hub (only on push to main)
    - name: Log in to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 7. Build & Push Docker image to Docker Hub (only on push to main)
    - name: Build & Push Docker image
      if: github.event_name == 'push'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:latest
          ${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:${{ github.sha }}

    # 7. Build & Push Docker image to Docker Hub (only on push to main)
    # - name: Build & Push Docker image
    #   if: github.event_name == 'push'
    #   run: |
    #     docker build \
    #     -t ${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:latest \
    #     -t ${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:${{ github.sha }} \
    #     .
    #     docker push ${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:latest
    #     docker push ${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:${{ github.sha }}