name: Test & Build Pipeline

on: 
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # New Caching step
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        pip install pytest flake8 httpx

    # 4. Run tests
    - name: Run tests
      run: pytest tests/ --maxfail=1 --disable-warnings -q

    # 5. Lint code
    - name: Link with flake8
      run:  flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics

    # 6. Build Docker image (only on push to main)
    # - name: Build Docker image
    #   if: github.event_name == 'push'
    #   run: |
    #     docker build \
    #     -t autoops-ai:latest \
    #     -t autoops-ai:${{ github.sha }} \
    #     .

    # 6. Login to Docker Hub (only on push to main)
    - name: Log in to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Set up Docker Buildx with BuildKit image and host network
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        driver-opts: |
          image=moby/buildkit:latest
          network=host

    # 7. Build & Push Docker image to Docker Hub (only on push to main)
    # - name: Build & Push Docker image
    #   if: github.event_name == 'push'
    #   run: |
    #     docker build \
    #     -t ${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:latest \
    #     -t ${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:${{ github.sha }} \
    #     .
    #     docker push ${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:latest
    #     docker push ${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:${{ github.sha }}

    # 7. Build & Push Docker image to Docker Hub (only on push to main)
    - name: Build & Push Docker image
      if: github.event_name == 'push'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:latest
          ${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:${{ github.sha }}
        cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:buildcache
        cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:buildcache,mode=max

    # 8. Checkout GitOps repo
    - name: Checkout GitOps repository
      if: github.event_name == 'push'
      uses: actions/checkout@v3
      with:
        repository: ${{ vars.MANIFESTS_REPO_NAME }}
        token: ${{ secrets.MANIFESTS_REPO_TOKEN }}
        path: ${{ vars.MANIFEST_PATH }}

    # 9. Update image tag in k8s manifest and push to the gitops repo (autoops-ai-gitops)
    - name: Update image tag in k8s manifests and push
      if: github.event_name == 'push'
      run: |
        cd ${{ vars.MANIFEST_PATH }}  # Change to cloned repo directory
        FILE="${{ vars.MANIFEST_PATH }}/${{ vars.MANIFEST_FILE }}"
        ls -l $FILE
        chmod 644 $FILE
        ls -l $FILE
        sed -i "s|image: .*|image: ${{ vars.DOCKERHUB_USERNAME }}/autoops-ai:${{ github.sha }}|g" $FILE
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add "${{ vars.MANIFEST_FILE }}"
        git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
        git push